### ISSUE TITLE
レイアウト修正

### ISSUE THREAD

**Issue by ryo-1123** [yraysou/sakura#42]
# 
### 概要
実際に使用してみてレイアウトの崩れ等があったため改修
# 
#### タスク
- [x] 印刷時に文字が潰れて見えるので修正
- [x] 電話番号の表示を削除
- [x] スクロールが出ないようにサイズ調整
- [x] IDとPasswordの文字大きく
- [x] 文言を入力（下記参照）
`パソコンからのダウンロードはコチラ【　http://gryymens.jpn.org/user　】`
`注意事項：Google Chromeからダウンロードをおすすめいたします。他のサイトからですと不具合が生じる場合がございます。`

### 期限
12/1
# 
### 対象箇所・ファイル名

# 
### その他・備考
すでにテストとして稼働しているので、優先度高めでお願いします
期限設けているので、必ず守ってください

**Comment by akarifukaya** [comment]
追加修正です。
ＩＤとＰａｓｓｗｏｒｄの文字も大きく修正をお願いいたします。

**Comment by akarifukaya** [comment]
追加修正➁
パソコンからのダウンロードはコチラ【　http://gryymens.jpn.org/user　】
注意事項：Google Chromeからダウンロードをおすすめいたします。他のサイトからですと不具合が生じる場合がございます。
以上

**Comment by ryo-1123** [comment]
@akarifukaya 注意事項についてですが、そこは推奨するだけでも問題ないのかなと思います。
理由としては、iphoneユーザでgoogle chromeを使用している人が少なく、その分ユーザの工程が増えてしまうからです。
そこはこっちの負担にはなりますが、僕のステージング環境で確認してsafariも対応する。とした方が良いかと思います。

**Comment by akarifukaya** [comment]
＠ryo-1123 
了解でいたしました。

**Comment by ryo-1123** [comment]
出来たのでクローズしまーす

**Comment by ryo-1123** [comment]
出来たのでクローズしまーす
